(function () {
  const n = (text, extra = {}) => ({ type: "narrate", text, ...extra });
  const s = (speaker, text, extra = {}) => ({ type: "say", speaker, text, ...extra });
  const c = (prompt, options, extra = {}) => ({ type: "choice", prompt, options, ...extra });
  const j = target => ({ type: "jump", target });
  const end = id => ({ type: "ending", id });
  const cast = (...ids) => ids;

  window.GAME_STORY = {
    prologue: [
      n("序章　潮声寄存处", { chapter: "序章 · 潮声寄存处", bg: "seaside", cast: [] }),
      n("八月的海风穿过半开的车窗，带着盐、铁轨和晒热木头的气味。离开星汐町七年后，我在同一个傍晚回来了。"),
      n("旧手机里躺着一封没有署名的邮件。附件是一段十九秒的录音，文件日期却显示在三天以后。"),
      n("录音里先是漫长的电流声，然后，一个熟悉又陌生的女声说——"),
      s("linxia", "陆遥，如果你听见这段话，请在夏祭烟火升起以前，来海岸电台。", { bg: "seaside", expression: "sad" }),
      n("她的声音被浪潮截断。邮件最后只有一串坐标，指向早已停用的星汐海岸电台。"),
      n("我告诉自己，时间戳可以伪造，声音也可以合成。可我还是买了当天最后一班车票。"),
      n("因为那声音属于林夏。七年前，在我不告而别的那天，她也曾站在月台上叫我的名字。"),
      n("列车减速。远处的海面被夕阳切成无数发亮的碎片，像某段被反复剪辑的记忆。"),
      n("广播报出“星汐站”。我拎起行李，发现自己的手心全是汗。"),
      n("有些城市用高楼确认时间，有些小镇用潮汐。星汐町显然属于后者。"),
      n("车门打开，蝉鸣和海风一起涌进车厢。站台尽头，有人踮着脚朝我挥手。"),
      j("arrival")
    ],

    arrival: [
      n("第一章　迟到七年的欢迎", { chapter: "第一章 · 迟到七年的欢迎", bg: "station", cast: cast("tangtao"), cg: "reunion" }),
      s("tangtao", "陆——遥——！你要是敢说没看见我，我就把你的行李扔进海里！", { active: "tangtao", expression: "angry" }),
      n("唐桃穿过空荡的站台冲过来。她的头发比记忆里短了，薄荷色发夹却还是当年那一枚。"),
      s("protagonist", "我只是在确认，七年不见，你的威胁有没有升级。"),
      s("tangtao", "当然升级了。现在我会先帮你买行李保险，再扔。"),
      n("她接过我最重的箱子，动作自然得像我们只是分别了一个周末。"),
      s("tangtao", "欢迎回来。旅馆给你留了房间，林夏在旧站房，沈月在资料馆。大家都在忙夏祭。", { expression: "smile" }),
      s("protagonist", "林夏……知道我回来吗？"),
      s("tangtao", "她就是那个最不擅长装作不知道的人。"),
      n("唐桃把一瓶冰凉的桃子汽水塞进我手里。玻璃瓶上凝着水珠，标签是她家老店沿用多年的手绘桃花。"),
      s("tangtao", "先说好，我接你不是因为想你。是镇公所缺一个免费劳动力。", { expression: "shy" }),
      s("protagonist", "那汽水呢？"),
      s("tangtao", "临期处理。"),
      n("我看了一眼瓶盖上的生产日期：今天早上。"),
      s("protagonist", "临期得很有前瞻性。"),
      s("tangtao", "闭嘴，喝你的。", { variant: "offering-soda" }),
      n("出站后，坡道两边的绣球花已经过了最盛的时候，仍固执地保留着蓝紫色。海岸线比记忆里更近，也更安静。", { cg: false }),
      s("tangtao", "海岸电台去年被雷击坏了。夏祭要做最后一次纪念广播，结果主机昨天又罢工。"),
      s("protagonist", "所以你们叫我这个做音频软件的人回来维修？"),
      s("tangtao", "一半。另一半是……我们在旧硬盘里发现了东西。"),
      s("protagonist", "三天后的录音？"),
      n("她骤然停住。汽水瓶里的玻璃珠发出清脆一响。"),
      s("tangtao", "你也收到了？", { expression: "surprised" }),
      n("这句话让海风忽然变冷。原来那封信并不只寄给了我。"),
      s("tangtao", "我们三个都收到过不同的片段。每一段，都像是夏祭当晚才会说的话。"),
      s("protagonist", "有人在恶作剧。"),
      s("tangtao", "林夏也这么说。沈月却把每个文件的校验码抄了三遍。"),
      n("前方的坡道分向三个方向：左边通往旧站房，右边通往海边商店街，更高处则是资料馆。"),
      s("tangtao", "你想先去哪里？我陪你。只是……别让她们等太久。", { expression: "sad" }),
      c("先去见谁？", [
        { text: "去旧站房找林夏", target: "meet_linxia", effects: { linxia: 2 }, unlock: "linxia" },
        { text: "陪唐桃走一遍商店街", target: "meet_tangtao", effects: { tangtao: 2 }, unlock: "tangtao" },
        { text: "去资料馆找沈月", target: "meet_shenyue", effects: { shenyue: 2 }, unlock: "shenyue" }
      ])
    ],

    meet_linxia: [
      n("旧站房的百叶窗漏进一排金色光柱。林夏站在拆开的收音机旁，长发被海风轻轻托起。", { bg: "workshop", cast: cast("linxia") }),
      s("linxia", "你比预计早到十一分钟。", { active: "linxia", expression: "surprised" }),
      s("protagonist", "听起来不像欢迎词。"),
      s("linxia", "我排练过更好的。可你真的站在这里，它们就全部失效了。", { expression: "shy" }),
      n("她伸手像要确认什么，最后只是替我取下肩头一片花瓣。"),
      s("linxia", "录音是从电台的自动归档系统发出的。程序是七年前你和我一起写的原型。"),
      s("protagonist", "那个只能定时录天气预报的半成品？"),
      s("linxia", "现在它会给过去寄信。至少表面上是。"),
      s("protagonist", "你害怕吗？"),
      s("linxia", "怕。不是怕未来，是怕它说中了我一直不敢说的事。", { expression: "sad" }),
      n("她移开目光，把一枚写着“RX-07”的旧钥匙放进我掌心。"),
      s("linxia", "一起把答案拆开吧。这次，不要中途消失。", { expression: "smile" }),
      s("protagonist", "这次我会把每根线都接回去。"),
      j("workshop")
    ],

    meet_tangtao: [
      n("唐桃坚持先绕商店街一圈。关门的唱片店、重新粉刷的旅馆、卖了二十年章鱼烧的推车，被她讲成一部语速飞快的地方史。", { bg: "seaside", cast: cast("tangtao") }),
      s("tangtao", "这里以前是游戏厅。你为了给我抓海豹玩偶，花光了返程车费。", { active: "tangtao", expression: "smile" }),
      s("protagonist", "最后不是抓到了吗？"),
      s("tangtao", "所以我还留着。不是因为喜欢，只是沉没成本太高。"),
      n("她指向旅馆二楼的窗户。窗帘后露出一只褪色的蓝色海豹。"),
      s("tangtao", "你走以后，我每年都想把它扔掉。每年夏祭，它又会自己回到窗边。", { expression: "sad" }),
      s("protagonist", "玩偶还会走路？"),
      s("tangtao", "不会。人会嘴硬。"),
      n("她说完便快步往前，耳尖被夕阳照得发红。"),
      s("tangtao", "那段录音里，我说‘别再等了’。可我不知道那是对谁说。"),
      s("protagonist", "如果是对我呢？"),
      s("tangtao", "那你最好在夏祭前证明，等待不是一件蠢事。", { expression: "angry" }),
      n("她回过头，笑容仍然明亮，眼睛里却藏着七个夏天。"),
      j("workshop")
    ],

    meet_shenyue: [
      n("资料馆建在旧灯塔下面。沈月正在给一箱磁带贴编号，银灰色长发从肩侧垂下，像月光落进纸页。", { bg: "observatory", cast: cast("shenyue") }),
      s("shenyue", "陆遥。登记表上写你会来，我还是不太相信。", { active: "shenyue", expression: "surprised" }),
      s("protagonist", "我们以前见过？"),
      s("shenyue", "你不记得很正常。七年前的广播比赛，我是坐在最后一排的记录员。"),
      n("她递来一本旧节目册。我的名字旁边，有一行工整的小字：‘把沉默也录进去的人。’"),
      s("protagonist", "这是你写的？"),
      s("shenyue", "你们都只在意声音。我那时觉得，停顿才是一个人真正想说的话。"),
      s("protagonist", "你收到的未来录音是什么？"),
      s("shenyue", "一句‘请替我保存空白’。声音是我的，但我从不说这么奇怪的话。"),
      n("她打开恒温柜。最里面放着一盘没有标签的母带，封口日期正是七年前我离开的那天。"),
      s("shenyue", "所有异常文件，都引用了这盘母带的索引。它或许不是未来，而是某段被我们漏掉的过去。", { variant: "holding-archive" }),
      s("protagonist", "你愿意一起听吗？"),
      s("shenyue", "我等这句话，等了七年。虽然你大概不是特意对我说的。", { expression: "sad" }),
      j("workshop")
    ],

    workshop: [
      n("第二章　十九秒之后", { chapter: "第二章 · 十九秒之后", bg: "workshop", cast: cast("tangtao", "linxia", "shenyue") }),
      n("傍晚六点，四个人围在海岸电台的旧控制台前。风扇发出拖拉机般的轰鸣，显示器却固执地停在蓝色启动画面。"),
      s("tangtao", "我宣布，由本镇最可靠的成年人负责精神支持。", { active: "tangtao" }),
      s("linxia", "也就是负责买晚饭。", { active: "linxia" }),
      s("shenyue", "以及不要碰任何闪烁的按钮。", { active: "shenyue" }),
      s("tangtao", "你们对可靠的定义是不是太狭窄了？", { expression: "angry" }),
      n("熟悉的斗嘴填满站房。我突然意识到，自己并没有被排除在这七年之外；她们只是各自留着一个空位。"),
      s("protagonist", "硬盘没有损坏。自动归档服务在每天凌晨三点，把一段缓存发给联系人列表。"),
      s("linxia", "可缓存目录里没有源文件。发送后就像凭空消失。"),
      s("shenyue", "收件时间分别提前五天、四天、三天。像在倒数。"),
      s("tangtao", "倒数到夏祭，然后旧电台‘砰’地变成时光机？"),
      s("protagonist", "更可能是定时任务读错了系统时间。未来录音只是早就录好的东西。"),
      s("linxia", "那就证明给我看。你负责软件，我查发射机。"),
      n("我接上自己的电脑。七年前写下的代码一行行滚过屏幕，幼稚的注释和拼错的变量名争先恐后地向我问好。"),
      s("protagonist", "这里有个叫 HEARTBEAT 的模块。谁取的名字？"),
      s("linxia", "你。说电台没声音时，也应该让远方知道它还活着。"),
      n("模块每隔一年录制一次环境声，叠加在旧母带上，再自动发送。它不是预测未来，而是把不同年份的声音混在了一起。"),
      s("shenyue", "可人声从哪里来？"),
      s("protagonist", "系统把频率相近的片段错误拼接。单词来自旧节目，顺序却是新的。"),
      s("tangtao", "所以是机器在拿我们的过去写同人小说？", { expression: "surprised" }),
      s("linxia", "比喻很糟，但大致正确。"),
      n("我们应该松一口气。可当我播放原始缓存，四个人都沉默了。"),
      s("linxia", "……请在烟火以前回来。", { active: "linxia", expression: "sad" }),
      s("tangtao", "……别再等了。", { active: "tangtao", expression: "sad" }),
      s("shenyue", "……替我保存空白。", { active: "shenyue", expression: "sad" }),
      n("这些词确实能在旧节目中找到。可机器为什么恰好拼出了我们最不敢面对的句子？概率低得近乎恶意。"),
      s("protagonist", "人脑擅长从噪声里寻找意义。也许我们听到的，只是自己。"),
      s("linxia", "那也意味着，它逼我们承认自己在想什么。"),
      n("窗外天色渐暗。远处试放了一枚烟火，闷响几秒后才抵达站房。"),
      s("shenyue", "还有最后一个未生成的缓存。任务时间是夏祭当晚八点。"),
      s("tangtao", "要关掉吗？只要拔掉电源，一切就结束了。"),
      s("linxia", "如果继续，它会读取今晚的直播，再把我们的声音拼成新的句子。"),
      s("protagonist", "技术上，我可以修复模块，让它不再乱序。但我们先决定：要不要听完最后一次。"),
      c("如何处理 HEARTBEAT 模块？", [
        { text: "和林夏一起修复，让它完成最后一次广播", target: "signal", effects: { linxia: 2, courage: 1 } },
        { text: "听唐桃的，先拔掉电源让大家喘口气", target: "signal", effects: { tangtao: 2, warmth: 1 } },
        { text: "按沈月的建议，完整备份再做决定", target: "signal", effects: { shenyue: 2, truth: 1 } }
      ])
    ],

    signal: [
      n("第三章　把杂音调成歌", { chapter: "第三章 · 把杂音调成歌", bg: "observatory", cast: cast("linxia", "tangtao", "shenyue") }),
      n("我们最终保留了模块，也给它加上人工确认。机器可以保存回声，却不能替人决定回声意味着什么。"),
      n("接下来的两天，海岸电台变成临时作战室。林夏修电路，我重写程序，沈月整理母带，唐桃负责把全镇的人和食物一起运来。"),
      s("tangtao", "午饭投票！咖喱、冷面，还是由我自由发挥？", { active: "tangtao" }),
      s("linxia", "前两项都可以，第三项违反安全条例。", { active: "linxia" }),
      s("shenyue", "资料显示，她上次自由发挥造成了三小时停水。", { active: "shenyue" }),
      s("tangtao", "那是水管对艺术缺乏包容。"),
      n("我笑出声。三个人同时看向我，又像什么都没发生一样继续忙。"),
      n("午后，林夏带我爬上发射塔检修天线。海面在脚下展开，镇子小得能被两只手捧住。"),
      s("linxia", "你当年为什么走？真正的理由。", { cast: cast("linxia"), active: "linxia", expression: "angry" }),
      s("protagonist", "父亲病倒后，我们连夜搬去省城。我以为只离开几周，后来每拖一天，就越不知道怎么解释。"),
      s("linxia", "所以你选择七年不解释。很符合程序员处理错误的方式：假装没看见日志。"),
      s("protagonist", "对不起。"),
      s("linxia", "这句我收下。但道歉不是句号，是重新开始的权限申请。", { expression: "smile" }),
      n("她把安全绳的锁扣重新按紧。动作很轻，却像给了我一个明确回答。"),
      n("傍晚，唐桃拉我去商店街收集夏祭祝福。每家店录十秒，最后剪成一段镇民广播。"),
      s("tangtao", "你还记得怎么举麦克风吗？别离太近，也别对着风。", { bg: "seaside", cast: cast("tangtao"), active: "tangtao", expression: "smile" }),
      s("protagonist", "当年的搭档老师，请多指教。"),
      s("tangtao", "当年的搭档至少不会突然失联。"),
      n("她说得像玩笑，脚步却慢了下来。"),
      s("tangtao", "其实我写过很多封信。每次都觉得下一封会更像我，所以一封也没寄。", { expression: "sad" }),
      s("protagonist", "现在这句话就很像你。"),
      s("tangtao", "哪一句？"),
      s("protagonist", "明明难过，还要假装在讲笑话。"),
      s("tangtao", "……那你就负责听懂。以后都负责。", { expression: "shy" }),
      n("晚上，沈月在资料馆教我修复那盘无名母带。我们戴着耳机，逐帧清理霉斑造成的爆音。"),
      s("shenyue", "这里有呼吸声。说话的人犹豫了四点二秒。", { bg: "observatory", cast: cast("shenyue"), active: "shenyue" }),
      s("protagonist", "你真的会记录每一次停顿？"),
      s("shenyue", "因为我的母亲忘得很快。她去世前，已经叫不出我的名字。我开始害怕，没有记录的东西就等于没发生。", { expression: "sad" }),
      s("protagonist", "所以你想保存空白。"),
      s("shenyue", "现在我明白了。空白不是缺失，是有人坐在身边，不必急着说话。", { expression: "smile" }),
      n("耳机里传来七年前的蝉鸣。我们安静地听完了整整一分钟。那一分钟没有名字，却确实存在。"),
      n("第三天清晨，修复后的母带终于显出隐藏轨。里面不是神秘预言，而是一场被忘记的试播。", { cg: "hidden-tape" }),
      s("linxia", "欢迎收听‘写给未来的星汐町’。", { bg: "workshop", cast: cast("linxia", "tangtao", "shenyue"), active: "linxia" }),
      s("tangtao", "未来的我！如果你变成无聊的大人，就回来喝汽水！", { active: "tangtao" }),
      s("protagonist", "未来的我们，无论在哪里，都别忘了回复。"),
      n("少年时代的我的声音从音箱里传出。紧接着，是一个很轻的陌生女声。"),
      s("shenyue", "我会替你们保存。", { active: "shenyue" }),
      n("沈月低下头。她终于认出，那是十七岁的自己。"),
      s("shenyue", "原来我真的参加过。只是一直站在门外。", { expression: "surprised" }),
      s("tangtao", "这次站里面。麦克风给你留最中间的位置。", { expression: "smile" }),
      s("linxia", "夏祭直播，四个人，一个都不能少。", { expression: "smile" }),
      n("就在此时，窗外落下第一滴雨。气象警报跳上屏幕：台风外围云系提前抵达，夏祭可能取消。", { cg: false }),
      j("quiet_night")
    ],

    quiet_night: [
      n("幕间　未寄出的夜航信", { chapter: "幕间 · 未寄出的夜航信", bg: "observatory", cast: cast("linxia", "tangtao", "shenyue") }),
      n("气象警报响起后，雨却迟迟没有落下。厚重云层压在海面上，像一封写到一半、还没决定是否寄出的信。"),
      s("linxia", "台风最快明晚到。今晚还能测试一次远距离接收。", { active: "linxia" }),
      s("tangtao", "也就是说，我们要在下雨前爬到灯塔顶？这种计划一般会出现在恐怖片开头。", { active: "tangtao" }),
      s("shenyue", "根据镇志，灯塔近四十年没有发生过超自然事故。", { active: "shenyue" }),
      s("tangtao", "你为什么特意强调‘超自然’？普通事故呢？"),
      s("shenyue", "有十七起。"),
      s("tangtao", "我现在退出还来得及吗？"),
      n("最后，我们还是带着便携接收机和四把手电筒上了山。唐桃一路走在最中间，坚持说那是最方便保护所有人的位置。"),
      n("灯塔早已改成无人值守，旋转镜仍按固定节奏扫过海面。每十二秒，白光从我们脸上缓慢掠过一次。"),
      s("protagonist", "七年前的试播，为什么没有正式播出？"),
      s("linxia", "那天你突然离开，比赛也因为设备故障取消。母带被送进资料馆，后来谁都没再提。", { active: "linxia" }),
      s("tangtao", "其实提过。我提议把你的部分剪掉，做成三人节目。", { active: "tangtao" }),
      s("shenyue", "林夏拒绝了。她说少一个人的合奏，不应该假装完整。", { active: "shenyue" }),
      n("林夏低头调节旋钮，没有否认。"),
      s("linxia", "当时觉得，保留原样才算诚实。现在看来，也可能只是我不肯接受变化。"),
      s("protagonist", "谢谢你没有把我剪掉。也对不起，让你们只能对着空轨道生气。"),
      s("tangtao", "生气是真的。但我们也不是每天围着你的空轨道生活。", { active: "tangtao" }),
      s("tangtao", "林夏考了无线电执照，沈月把资料馆从漏雨仓库变成了镇上最漂亮的地方。我还拿过两届商店街销量冠军。"),
      s("shenyue", "参赛店铺一共三家。", { active: "shenyue" }),
      s("tangtao", "冠军就是冠军，请尊重统计结果。"),
      n("我望着她们。离开的七年不是故事里可以一笔带过的空白，而是她们真实走过的两千多个日夜。"),
      s("protagonist", "我不想要求一切回到从前。那对现在的你们不公平。"),
      s("shenyue", "记录也不是为了复原过去。好的档案，会告诉后来的人：事情从这里继续。", { active: "shenyue" }),
      n("接收机忽然亮起绿色指示灯。林夏戴上耳机，示意我们安静。"),
      s("linxia", "收到一段很弱的海事信号。不是我们的频率。", { active: "linxia", variant: "tuning-radio" }),
      n("杂音深处，一个男孩断断续续地报告位置。他和父亲的小艇发动机熄火，手机也只剩最后一点电。"),
      s("protagonist", "能回传吗？"),
      s("linxia", "便携机功率不够。唐桃，灯塔值班室还有有线电话吗？"),
      s("tangtao", "线路去年拆了。但山腰的气象站有中继电源，我知道备用钥匙在哪。", { active: "tangtao" }),
      s("shenyue", "我记得那条航道的旧编号。坐标末位可能被杂音盖住，我去查纸质海图。", { active: "shenyue", variant: "holding-archive" }),
      n("四个人同时行动。没有争论，也没有谁等待命令。林夏持续呼叫小艇，我和唐桃接通中继，沈月用三版海图交叉确认漂流方向。", { cg: "lighthouse-rescue" }),
      n("十六分钟后，港口救援队回应。小艇在防波堤外两海里被找到，男孩和父亲都平安。"),
      s("tangtao", "看吧，电台才不是什么只会翻旧账的机器。", { active: "tangtao", expression: "smile" }),
      s("linxia", "它本来就是用来让没有被听见的人被听见。", { active: "linxia", expression: "smile" }),
      n("林夏摘下耳机，额前全是汗。沈月在救援记录上写下时间，然后难得地主动留了一行空白。"),
      s("shenyue", "这一行留给他们回家以后自己补。", { active: "shenyue", expression: "smile" }),
      n("唐桃从背包底部翻出四瓶汽水。她得意地宣布，可靠的成年人永远会准备庆功物资。", { cg: false }),
      s("protagonist", "所以你背包一路叮当响，是因为这个？"),
      s("tangtao", "还因为我带了扳手、雨衣、创可贴和那只蓝色海豹。", { active: "tangtao" }),
      s("linxia", "为什么带海豹？"),
      s("tangtao", "精神支持。它在这方面比某些失联七年的人专业。"),
      n("我们坐在灯塔台阶上碰杯。远处救援船的灯光沿海岸缓慢移动，最终与港口的灯火汇合。"),
      s("protagonist", "我以前总觉得，只有说出漂亮的话才算回复。结果越想说好，就拖得越久。"),
      s("linxia", "无线电的第一课不是说话，是先确认收到。", { active: "linxia" }),
      s("tangtao", "第二课是请客。欠了七年的份，利息很高。", { active: "tangtao" }),
      s("shenyue", "第三课是允许停顿。只要双方都知道对方还在。", { active: "shenyue" }),
      n("我认真地点头。海风把瓶口的甜味吹散，灯塔的白光又一次越过我们。"),
      n("那一夜，我们没有解决关于未来的任何问题，却救回了两个正在海上等待回应的人。也许这已经是旧电台能给出的最好答案。"),
      n("下山时，第一阵雨终于落下。林夏撑开伞，唐桃把外套罩在接收机上，沈月护住那本留有空行的记录册。"),
      n("而我走在她们中间，第一次没有把‘以后再说’当成沉默的借口。"),
      j("storm")
    ],

    storm: [
      n("第四章　暴雨静默时", { chapter: "第四章 · 暴雨静默时", bg: "rain", cast: cast("linxia", "tangtao", "shenyue") }),
      n("傍晚六点，暴雨淹没了通往广场的路。摊位紧急撤收，烟火船返港，原定的夏祭广播也被通知终止。"),
      s("tangtao", "就这样结束？大家准备了一个月。", { active: "tangtao", expression: "sad" }),
      s("linxia", "发射机能运行，但主电网随时会断。", { active: "linxia" }),
      s("shenyue", "资料馆有应急蓄电池，可以维持四十分钟。", { active: "shenyue" }),
      s("protagonist", "广场办不了，就让每个人在家里听。我们做一场没有烟火的夏祭。"),
      s("tangtao", "商店街有十二台备用收音机。我去送。"),
      s("linxia", "我把功率降到安全值，覆盖全镇足够。"),
      s("shenyue", "我联系镇民，收集想在今晚播放的留言。"),
      n("计划没有经过讨论就成形了。我们分头冲进雨里，像七年前那群相信一根天线能连接世界的孩子。"),
      n("七点二十分，电网中断。应急灯亮起，旧站房只剩设备的微光和窗外倾斜的雨线。"),
      s("linxia", "蓄电池接入。载波稳定。", { active: "linxia" }),
      s("shenyue", "收到四十七条留言，还在增加。", { active: "shenyue" }),
      s("tangtao", "最后一台收音机送到海边诊所。全镇都在等。", { active: "tangtao" }),
      n("七点五十九分，HEARTBEAT 模块弹出最终确认：是否开始记录？"),
      s("protagonist", "开始吧。这次不让机器替我们拼句子。"),
      n("红色录音灯亮起。林夏推高电平，唐桃把窗关紧，沈月摊开稿纸。我对着麦克风深吸一口气。", { cg: "storm-broadcast" }),
      s("protagonist", "晚上好，星汐町。这里是海岸电台。雨暂时藏起了烟火，但没有带走这个夏天。"),
      n("我们播放面包店老板给远方女儿的问候，渔船船长报来的平安，孩子们跑调的合唱，还有旅馆客人用五种方言说的晚安。"),
      n("雨声渐弱。镇上的灯一盏盏熄着，收音机的微光却在窗边连成另一条星河。"),
      s("tangtao", "下一条留言没有署名。‘谢谢那个终于回来的人。’哎呀，会是谁呢？", { active: "tangtao", expression: "smile" }),
      s("linxia", "播音员请不要擅自追查听众隐私。", { active: "linxia" }),
      s("shenyue", "根据笔迹，我可以——", { active: "shenyue" }),
      s("tangtao", "沈月也不许破案！"),
      n("笑声透过电波传遍小镇。那一刻，没有人需要知道未来。"),
      n("八点三十八分，云层裂开一道缝。被取消的烟火船在港内点燃一枚小小的试验弹，金色光芒映亮湿漉漉的窗。"),
      s("linxia", "最后一分钟。陆遥，你来选结束曲。", { active: "linxia", cg: false }),
      n("控制台上放着三盘刚刚录好的磁带：星光下的校准声、商店街的笑声、资料馆的一分钟空白。"),
      n("我伸出手。选一盘，就意味着对某个人说出迟到已久的回答。"),
      c("夏祭直播的最后一分钟，播放哪一盘？", [
        { text: "林夏的《星光抵达以前》", target: "route_linxia", effects: { linxia: 3 }, unlock: "ending-linxia" },
        { text: "唐桃的《桃子汽水不会过期》", target: "route_tangtao", effects: { tangtao: 3 }, unlock: "ending-tangtao" },
        { text: "沈月的《写给明天的空白页》", target: "route_shenyue", effects: { shenyue: 3 }, unlock: "ending-shenyue" }
      ])
    ],

    route_linxia: [
      n("终章　星光抵达以前", { chapter: "终章 · 星光抵达以前", bg: "dawn", cast: cast("linxia") }),
      n("直播结束后，林夏独自爬上发射塔平台。我跟上去时，东方已经显出很淡的蓝。"),
      s("linxia", "你选了那盘磁带。是因为内容最好，还是因为录音的人？", { active: "linxia", expression: "shy" }),
      s("protagonist", "如果我说两者都有，会不会显得像在逃避？"),
      s("linxia", "会。但可以给你一次重新作答。"),
      s("protagonist", "因为是你。七年前我没能回复的人，现在就在这里。"),
      n("她望着海平线。天线在风里轻轻震动，发出只有站得足够近才能听见的低鸣。"),
      s("linxia", "我一直想造一台不会错过任何信号的接收机。后来才知道，不回复的人，再强的天线也没用。", { expression: "sad" }),
      s("protagonist", "那我从今天开始补交回复。可能会很长。"),
      s("linxia", "允许分期，但不许再次断线。"),
      n("她伸出小指，又觉得幼稚似的想收回。我先一步勾住。", { cg: "ending-linxia" }),
      s("protagonist", "林夏，我喜欢你。不是七年前的存档，是现在。"),
      s("linxia", "确认收到。信号强度……超出量程。", { expression: "shy" }),
      n("她笑起来，眼角却有微光。太阳越过海面，把我们的影子拉向重新醒来的小镇。"),
      n("后来，海岸电台每周只播一次。林夏负责设备，我负责节目；我们把 HEARTBEAT 改成一封真正写给未来的公开信。"),
      n("每期结尾，她都会说：‘这里是星汐町。无论你在哪里，请记得回复。’"),
      n("而我总会在话筒外回答她：‘收到。’"),
      end("linxia")
    ],

    route_tangtao: [
      n("终章　桃子汽水不会过期", { chapter: "终章 · 桃子汽水不会过期", bg: "dawn", cast: cast("tangtao") }),
      n("直播结束，唐桃抱着空汽水箱往旅馆走。雨后的坡道很滑，她却故意走得飞快。"),
      s("protagonist", "你再快一点，我又要跟丢了。", { active: "tangtao" }),
      s("tangtao", "谁让你跟了？", { expression: "angry" }),
      s("protagonist", "七年前没跟上。这次想补考。"),
      n("她在自动贩卖机前停下，投了两枚硬币。机器滚出最后两瓶桃子汽水。"),
      s("tangtao", "那盘磁带，是我十七岁时录的。‘不会过期’根本是骗人的。汽水会跑气，人也会变。", { expression: "sad" }),
      s("protagonist", "可喜欢过的味道不会消失。再喝到时，还是认得。"),
      s("tangtao", "你这是在说汽水？"),
      s("protagonist", "我在说那个每年把海豹玩偶摆回窗边的人。"),
      n("玻璃珠咚地落下。她低头喝了一大口，像给自己争取勇气。"),
      s("tangtao", "陆遥，我等你不是因为停在原地。我开了店，学会修水管，还把这条街的人都照顾得很好。"),
      s("protagonist", "我知道。所以我不是来带你离开。我想问，能不能让我加入你正在过的生活。"),
      s("tangtao", "试用期很长，工资很低，还要每天听老板讲冷笑话。"),
      s("protagonist", "什么时候上班？"),
      s("tangtao", "……现在。先负责牵手。", { expression: "shy" }),
      n("她把微凉的手塞进我掌心，另一只手高高举起汽水，对着渐亮的天空碰杯。", { cg: "ending-tangtao" }),
      n("后来，旅馆一楼多了一间小小的录音咖啡馆。客人可以留下一分钟声音，寄给一年后的自己。"),
      n("唐桃把那只蓝色海豹放在收银台最显眼的位置，标签上写着：非卖品，以及，等待已经结束。"),
      end("tangtao")
    ],

    route_shenyue: [
      n("终章　写给明天的空白页", { chapter: "终章 · 写给明天的空白页", bg: "dawn", cast: cast("shenyue") }),
      n("直播结束后，沈月把那盘空白磁带带回资料馆。我陪她走过雨后的石阶，谁也没有急着开口。"),
      s("shenyue", "你真的播放了一分钟空白。收听事故报告会很好写。", { active: "shenyue" }),
      s("protagonist", "那一分钟里有雨、呼吸，还有某个人翻动稿纸的声音。并不空。"),
      s("shenyue", "你听见了？", { expression: "surprised" }),
      s("protagonist", "因为我在认真听你。"),
      n("她抱紧磁带盒，像抱住一件终于不必解释用途的宝物。"),
      s("shenyue", "我保存了太多东西。票根、声音、别人的告别。好像只要编号足够准确，就不会再次失去谁。", { expression: "sad" }),
      s("protagonist", "记录可以证明发生过，却不能替你生活。"),
      s("shenyue", "那你愿意陪我制造一些来不及编号的记忆吗？", { expression: "shy" }),
      s("protagonist", "第一件就从现在开始。沈月，我喜欢和你一起沉默，也喜欢听你说话。"),
      n("她先是怔住，然后露出一个比黎明更轻的笑。"),
      s("shenyue", "这句话需要永久保存。", { expression: "smile" }),
      s("protagonist", "不必。我可以每天说。"),
      s("shenyue", "那……存储压力会很大。"),
      s("protagonist", "资料馆员小姐，请想办法扩容。"),
      n("她伸手牵住我。掌心相触的一刻，我们都没有说话，也没有觉得缺少什么。", { cg: "ending-shenyue" }),
      n("后来，资料馆新增了“未完成档案”区。每个人都能留下一页空白，等未来某天回来续写。"),
      n("我和沈月的那一页始终没有归档。因为每次想写下结尾，我们都会发现，明天还有新的内容。"),
      end("shenyue")
    ]
  };
})();
